export const autoSuggestions = [
  { text: "Africaghanistan", value: "004", category: "Asia" },
  { text: "Albania", value: "008", category: "Europe" },
  { text: "Algeria", value: "012", category: "Africarica" },
  { text: "American Samoa", value: "016", category: "Oceania" },
  { text: "Andorra", value: "020", category: "Europe" },
  { text: "Angola", value: "024", category: "Africa" },
  { text: "Anguilla", value: "660", category: "North America" },
  { text: "Antigua and Barbuda", value: "028", category: "North America" },
  { text: "Argentina", value: "032", category: "South America" },
  { text: "Armenia", value: "051", category: "Asia" },
  { text: "Aruba", value: "533", category: "South America" },
  { text: "Australia", value: "036", category: "Oceania" },
  { text: "Azerbaijan", value: "031", category: "Asia" },
  { text: "Bahamas", value: "044", category: "North America" },
  { text: "Bahrain", value: "048", category: "Asia" },
  { text: "Bangladesh", value: "050", category: "Asia" },
  { text: "Barbados", value: "052", category: "North America" },
  { text: "Belarus", value: "112", category: "Europe" },
  { text: "Belgium", value: "056", category: "Europe" },
  { text: "Belize", value: "084", category: "North America" },
  { text: "Benin", value: "204", category: "Africa" },
  { text: "Bermuda", value: "060", category: "North America" },
  { text: "Bhutan", value: "064", category: "Asia" },
  {
    text: "Bolivia (Plurinational State of)",
    value: "068",
    category: "South America",
  },
  { text: "Bosnia and Herzegovina", value: "070", category: "Europe" },
  { text: "Botswana", value: "072", category: "Africa" },
  { text: "Brazil", value: "076", category: "South America" },
  { text: "British Indian Ocean Territory", value: "086", category: "Africa" },
  { text: "Virgin Islands (British)", value: "092", category: "North America" },
  { text: "Virgin Islands (U.S.)", value: "850", category: "North America" },
  { text: "Brunei Darussalam", value: "096", category: "Asia" },
  { text: "Bulgaria", value: "100", category: "Europe" },
  { text: "Burkina Faso", value: "854", category: "Africa" },
  { text: "Burundi", value: "108", category: "Africa" },
  { text: "Cambodia", value: "116", category: "Asia" },
  { text: "Cameroon", value: "120", category: "Africa" },
  { text: "Canada", value: "124", category: "North America" },
  { text: "Cabo Verde", value: "132", category: "Africa" },
  { text: "Cayman Islands", value: "136", category: "North America" },
  { text: "Central Africarican Republic", value: "140", category: "Africa" },
  { text: "Chile", value: "152", category: "South America" },
  { text: "China", value: "156", category: "Asia" },
  { text: "Colombia", value: "170", category: "South America" },
  { text: "Comoros", value: "174", category: "Africa" },
  { text: "Congo", value: "178", category: "Africa" },
  {
    text: "Congo (Democratic Republic of the)",
    value: "180",
    category: "Africa",
  },
  { text: "Cook Islands", value: "184", category: "Oceania" },
  { text: "Costa Rica", value: "188", category: "North America" },
  { text: "Croatia", value: "191", category: "Europe" },
  { text: "Cuba", value: "192", category: "North America" },
  { text: "Cuba", value: "192", category: "North America" },
  { text: "Cyprus", value: "196", category: "Europe" },
  { text: "Czech Republic", value: "203", category: "Europe" },
  { text: "Denmark", value: "208", category: "Europe" },
  { text: "Djibouti", value: "262", category: "Africa" },
  { text: "Dominica", value: "212", category: "North America" },
  { text: "Dominican Republic", value: "214", category: "North America" },
  { text: "Ecuador", value: "218", category: "South America" },
  { text: "Egypt", value: "818", category: "Africa" },
  { text: "El Salvador", value: "222", category: "North America" },
  { text: "Equatorial Guinea", value: "226", category: "Africa" },
  { text: "Eritrea", value: "232", category: "Africa" },
  { text: "Estonia", value: "233", category: "Europe" },
  { text: "Ethiopia", value: "231", category: "Africa" },
  {
    text: "Falkland Islands (Malvinas)",
    value: "238",
    category: "South America",
  },
  { text: "Faroe Islands", value: "234", category: "Europe" },
  { text: "Fiji", value: "242", category: "Oceania" },
  { text: "Finland", value: "246", category: "Europe" },
  { text: "France", value: "250", category: "Europe" },
  { text: "French Guiana", value: "254", category: "South America" },
  { text: "French Polynesia", value: "258", category: "Oceania" },
  { text: "Gabon", value: "266", category: "Africa" },
  { text: "Gambia", value: "270", category: "Africa" },
  { text: "Georgia", value: "268", category: "Asia" },
  { text: "Germany", value: "276", category: "Europe" },
  { text: "Ghana", value: "288", category: "Africa" },
  { text: "Gibraltar", value: "292", category: "Europe" },
  { text: "Greece", value: "300", category: "Europe" },
  { text: "Greenland", value: "304", category: "North America" },
  { text: "Grenada", value: "308", category: "North America" },
  { text: "Guadeloupe", value: "312", category: "North America" },
  { text: "Guam", value: "316", category: "Oceania" },
  { text: "Guatemala", value: "320", category: "North America" },
  { text: "Guinea", value: "324", category: "Africa" },
  { text: "Guinea-Bissau", value: "624", category: "Africa" },
  { text: "Guyana", value: "328", category: "South America" },
  { text: "Haiti", value: "332", category: "Americas" },
  { text: "Holy See", value: "336", category: "Europe" },
  { text: "Honduras", value: "340", category: "North America" },
  { text: "Hong Kong", value: "344", category: "Asia" },
  { text: "Hungary", value: "348", category: "Europe" },
  { text: "Iceland", value: "352", category: "Europe" },
  { text: "India", value: "356", category: "Asia" },
  { text: "Indonesia", value: "360", category: "Asia" },
  { text: "Côte d'Ivoire", value: "384", category: "Africa" },
  { text: "Iran (Islamic Republic of)", value: "364", category: "Asia" },
  { text: "Iraq", value: "368", category: "Asia" },
  { text: "Ireland", value: "372", category: "Europe" },
  { text: "Israel", value: "376", category: "Asia" },
  { text: "Italy", value: "380", category: "Europe" },
  { text: "Jamaica", value: "388", category: "North America" },
  { text: "Japan", value: "392", category: "Asia" },
  { text: "Jordan", value: "400", category: "Asia" },
  { text: "Kazakhstan", value: "398", category: "Asia" },
  { text: "Kenya", value: "404", category: "Africa" },
  { text: "Kiribati", value: "296", category: "Oceania" },
  { text: "Kuwait", value: "414", category: "Asia" },
  { text: "Kyrgyzstan", value: "417", category: "Asia" },
  { text: "Lao People's Democratic Republic", value: "418", category: "Asia" },
  { text: "Latvia", value: "428", category: "Europe" },
  { text: "Lebanon", value: "422", category: "Asia" },
  { text: "Lesotho", value: "426", category: "Africa" },
  { text: "Liberia", value: "430", category: "Africa" },
  { text: "Libya", value: "434", category: "Africa" },
  { text: "Liechtenstein", value: "438", category: "Europe" },
  { text: "Lithuania", value: "440", category: "Europe" },
  { text: "Luxembourg", value: "442", category: "Europe" },
  { text: "Macao", value: "446", category: "Asia" },
  {
    text: "Macedonia (the former Yugoslav Republic of)",
    value: "807",
    category: "Europe",
  },
  { text: "Madagascar", value: "450", category: "Africa" },
  { text: "Malawi", value: "454", category: "Africa" },
  { text: "Malaysia", value: "458", category: "Asia" },
  { text: "Maldives", value: "462", category: "Asia" },
  { text: "Mali", value: "466", category: "Africa" },
  { text: "Malta", value: "470", category: "Europe" },
  { text: "Marshall Islands", value: "584", category: "Oceania" },
  { text: "Martinique", value: "474", category: "Americas" },
  { text: "Mauritania", value: "478", category: "Africa" },
  { text: "Mauritius", value: "480", category: "Africa" },
  { text: "Mayotte", value: "175", category: "Africa" },
  { text: "Mexico", value: "484", category: "North America" },
  {
    text: "Micronesia (Federated States of)",
    value: "583",
    category: "Oceania",
  },
  { text: "Moldova (Republic of)", value: "498", category: "Europe" },
  { text: "Monaco", value: "492", category: "Europe" },
  { text: "Mongolia", value: "496", category: "Asia" },
  { text: "Montenegro", value: "499", category: "Europe" },
  { text: "Montserrat", value: "500", category: "North America" },
  { text: "Morocco", value: "504", category: "Africa" },
  { text: "Mozambique", value: "508", category: "Africa" },
  { text: "Myanmar", value: "104", category: "Asia" },
  { text: "Namibia", value: "516", category: "Africa" },
  { text: "Nauru", value: "520", category: "Oceania" },
  { text: "Nepal", value: "524", category: "Asia" },
  { text: "Netherlands", value: "528", category: "Europe" },
  { text: "New Caledonia", value: "540", category: "Oceania" },
  { text: "New Zealand", value: "554", category: "Oceania" },
  { text: "Nicaragua", value: "558", category: "North America" },
  { text: "Niger", value: "562", category: "Africa" },
  { text: "Nigeria", value: "566", category: "Africa" },
  { text: "Niue", value: "570", category: "Oceania" },
  { text: "Norfolk Island", value: "574", category: "Oceania" },
  {
    text: "Korea (Democratic People's Republic of)",
    value: "408",
    category: "Asia",
  },
  { text: "Northern Mariana Islands", value: "580", category: "Oceania" },
  { text: "Norway", value: "578", category: "Europe" },
  { text: "Oman", value: "512", category: "Asia" },
  { text: "Pakistan", value: "586", category: "Asia" },
  { text: "Palau", value: "585", category: "Oceania" },
  { text: "Palestine, State of", value: "275", category: "Asia" },
  { text: "Panama", value: "591", category: "North America" },
  { text: "Papua New Guinea", value: "598", category: "Oceania" },
  { text: "Paraguay", value: "600", category: "South America" },
  { text: "Peru", value: "604", category: "South America" },
  { text: "Philippines", value: "608", category: "Asia" },
  { text: "Poland", value: "616", category: "Europe" },
  { text: "Portugal", value: "620", category: "Europe" },
  { text: "Puerto Rico", value: "630", category: "North America" },
  { text: "Qatar", value: "634", category: "Asia" },
  { text: "Republic of Kosovo", value: "383", category: "Europe" },
  { text: "Réunion", value: "638", category: "Africa" },
  { text: "Romania", value: "642", category: "Europe" },
  { text: "Russian Federation", value: "643", category: "Europe" },
  { text: "Rwanda", value: "646", category: "Africa" },
  { text: "Saint Barthélemy", value: "652", category: "North America" },
  {
    text: "Saint Helena, Ascension and Tristan da Cunha",
    value: "654",
    category: "Africa",
  },
  { text: "Saint Kitts and Nevis", value: "659", category: "North America" },
  { text: "Saint Lucia", value: "662", category: "North America" },
  {
    text: "Saint Martin (French part)",
    value: "663",
    category: "North America",
  },
  {
    text: "Saint Pierre and Miquelon",
    value: "666",
    category: "North America",
  },
  {
    text: "Saint Vincent and the Grenadines",
    value: "670",
    category: "North America",
  },
  { text: "Samoa", value: "882", category: "Oceania" },
  { text: "San Marino", value: "674", category: "Europe" },
  { text: "Sao Tome and Principe", value: "678", category: "Africa" },
  { text: "Saudi Arabia", value: "682", category: "Asia" },
  { text: "Senegal", value: "686", category: "Africa" },
  { text: "Serbia", value: "688", category: "Europe" },
  { text: "Seychelles", value: "690", category: "Africa" },
  { text: "Sierra Leone", value: "694", category: "Africa" },
  { text: "Singapore", value: "702", category: "Asia" },
  { text: "Slovakia", value: "703", category: "Europe" },
  { text: "Slovenia", value: "705", category: "Europe" },
  { text: "Solomon Islands", value: "090", category: "Oceania" },
  { text: "Somalia", value: "706", category: "Africa" },
  { text: "South Africarica", value: "710", category: "Africa" },
  { text: "Korea (Republic of)", value: "410", category: "Asia" },
  { text: "Spain", value: "724", category: "Europe" },
  { text: "Sri Lanka", value: "144", category: "Asia" },
  { text: "Sudan", value: "729", category: "Africa" },
  { text: "Suriname", value: "740", category: "South America" },
  { text: "Swaziland", value: "748", category: "Africa" },
  { text: "Sweden", value: "752", category: "Europe" },
  { text: "Switzerland", value: "756", category: "Europe" },
  { text: "Syrian Arab Republic", value: "760", category: "Asia" },
  { text: "Taiwan", value: "158", category: "Asia" },
  { text: "Tajikistan", value: "762", category: "Asia" },
  { text: "Tanzania, United Republic of", value: "834", category: "Africa" },
  { text: "Thailand", value: "764", category: "Asia" },
  { text: "Timor-Leste", value: "626", category: "Asia" },
  { text: "Togo", value: "768", category: "Africa" },
  { text: "Tokelau", value: "772", category: "Oceania" },
  { text: "Tonga", value: "776", category: "Oceania" },
  { text: "Trinidad and Tobago", value: "780", category: "South America" },
  { text: "Tunisia", value: "788", category: "Africa" },
  { text: "Turkey", value: "792", category: "Asia" },
  { text: "Turkmenistan", value: "795", category: "Asia" },
  { text: "Turks and Caicos Islands", value: "796", category: "North America" },
  { text: "Tuvalu", value: "798", category: "Oceania" },
  { text: "Uganda", value: "800", category: "Africa" },
  { text: "Ukraine", value: "804", category: "Europe" },
  { text: "United Arab Emirates", value: "784", category: "Asia" },
  {
    text: "United Kingdom of Great Britain and Northern Ireland",
    value: "826",
    category: "Europe",
  },
  { text: "United States of America", value: "840", category: "North America" },
  { text: "Uruguay", value: "858", category: "South America" },
  { text: "Uzbekistan", value: "860", category: "Asia" },
  { text: "Vanuatu", value: "548", category: "Oceania" },
  {
    text: "Venezuela (Bolivarian Republic of)",
    value: "862",
    category: "South America",
  },
  { text: "Viet Nam", value: "704", category: "Asia" },
  { text: "Wallis and Futuna", value: "876", category: "Oceania" },
  { text: "Wallis and Futuna", value: "876", category: "Oceania" },
  { text: "Yemen", value: "887", category: "Asia" },
  { text: "Zambia", value: "894", category: "Africa" },
  { text: "Zimbabwe", value: "716", category: "Africa" },
];
