name: Publish Packages

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main # Run only on push events to the main branch

env:
  GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pnpm
        uses: pnpm/action-setup@v4
        # will install the version specified in the packageManager field in the package.json.

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install

      - name: Git configuration
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git fetch --all
          git switch $(basename ${{ github.ref }})

      - name: Build packages
        run: |
          pnpm run grn:build
          pnpm run grw:build

      - name: Push changes and tags
        run: |
          pnpm run changeset:publish
          git push --tags
